# Generated by Django 5.2.8 on 2025-11-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_purchaserequest_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
