# Generated by Django 5.2.8 on 2025-11-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0003_purchaserequest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='proforma_raw_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='receipt_raw_text',
            field=models.TextField(blank=True),
        ),
    ]
