# Generated by Django 5.2.8 on 2025-11-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0004_purchaserequest_proforma_raw_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='proforma_raw_text',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='receipt_raw_text',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='submitted_at',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='version',
        ),
        migrations.RemoveField(
            model_name='receiptvalidationresult',
            name='validated_by',
        ),
    ]
